/// <reference types="astro/client" />

/**
 * PG Hunter runtime types.
 *
 * `worker-configuration.d.ts` is generated by the Cloudflare Vite plugin (and
 * `npx wrangler types`) but is excluded from the TS program (see tsconfig.json)
 * because its embedded workerd runtime types redeclare web globals (Element,
 * Response, …) and break the DOM types used by client-side scripts. Instead we
 * declare the small surface this app actually uses.
 */

declare module 'cloudflare:workers' {
  export const env: Cloudflare.Env;
}

declare namespace Cloudflare {
  interface Env {
    /** D1 binding configured in wrangler.toml. */
    DB: D1Database;
    /** R2 bucket for owner-uploaded images/documents (wrangler.toml). */
    MEDIA: R2Bucket;
    /** Comma-separated emails granted admin access (secret / .dev.vars). */
    ADMIN_EMAILS?: string;
    /** Google OAuth client id (secret: wrangler / .dev.vars). */
    GOOGLE_CLIENT_ID?: string;
    /** Google OAuth client secret (secret: wrangler / .dev.vars). */
    GOOGLE_CLIENT_SECRET?: string;
    /** Optional site URL override for OAuth redirect URIs. */
    SITE_URL?: string;
  }
}

/* Minimal D1 surface used by the API (see Cloudflare D1 docs). */
interface D1Result<T = unknown> {
  results: T[];
  success: boolean;
  meta?: Record<string, unknown>;
}

interface D1PreparedStatement {
  bind(...values: unknown[]): D1PreparedStatement;
  first<T = unknown>(): Promise<T | null>;
  all<T = unknown>(): Promise<D1Result<T>>;
  run(): Promise<{ success: boolean; meta?: Record<string, unknown> }>;
}

interface D1Database {
  prepare(query: string): D1PreparedStatement;
}

/* Minimal R2 surface used by the API (see Cloudflare R2 docs). */
interface R2Object {
  key: string;
  size: number;
  httpMetadata?: { contentType?: string; cacheControl?: string };
}

interface R2ObjectBody extends R2Object {
  body: ReadableStream | null;
}

interface R2PutOptions {
  httpMetadata?: { contentType?: string; cacheControl?: string };
}

interface R2Bucket {
  put(
    key: string,
    value: ArrayBuffer | ReadableStream | string,
    options?: R2PutOptions
  ): Promise<R2Object>;
  get(key: string): Promise<R2ObjectBody | null>;
  delete(key: string): Promise<void>;
}
